server: 
  port: 9002
spring:
  application:
    name: tensquare_recruit #服务名称
  datasource:
    url: jdbc:mysql://localhost:3306/tensquare_recruit?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa: 
    database: MySQL
    show-sql: true
